### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by KogutGaming** [JagTheFriend/Drednot-Dashboard-Prettifer#1]
how to use this?
on replit

**Comment by JagTheFriend** [comment]
I wouldn't recommend you to run it on replit because when you'll try to run the project (after installing all the dependencies),
you'll get this error:
![image](https://user-images.githubusercontent.com/70753983/149615375-f2e7133c-c671-49a8-8f1f-53cff1ae198c.png)
Which is why I recommend you to run this project locally (on your device) instead of relying on replit

**Comment by KogutGaming** [comment]
> 
> HOW TO UPDATE NODE TO VERSION 17 IN REPL.IT
> At first go to your repl or if you don't have any just create one
> Go to the shell prompt and run the following code
> npm init -y && npm i --save-dev node@17 && npm config set prefix=$(pwd)/node_modules/node && export PATH=$(pwd)/node_modules/node/bin:$PATH
> 
> 
> And Also Create a .replit File Andcopy & paste code below... 
> run = "node_modules/.bin/node index.js"

**Comment by KogutGaming** [comment]
try this?

**Comment by KogutGaming** [comment]
or idk

**Comment by JagTheFriend** [comment]
Still nope, 
I got this error:
![image](https://user-images.githubusercontent.com/70753983/150204115-0c1fa2d6-bf74-4079-ac39-0183f664fdb3.png)

**Comment by JagTheFriend** [comment]
Have a look at this [repl](https://replit.com/@JagTheFriend/Drednot-Dashboard-Prettifer)

**Comment by KogutGaming** [comment]
hmm

**Comment by KogutGaming** [comment]
try heroku
[](https://dashboard.heroku.com/apps)

**Comment by KogutGaming** [comment]
https://dashboard.heroku.com/apps

**Comment by JagTheFriend** [comment]
> try heroku

Its not  a web application, so I don't think it would work over there.
